version: '3'

services:
  api:
    build: ./api
    container_name: dendriteai-api-c
    ports:
      - '5000:8080'
    environment:
      - MONGO_URI=mongodb+srv://kalwarsushil2:sushil69@nodeexpressproject.chjptls.mongodb.net/internship?retryWrites=true&w=majority
    depends_on:
      - mongo
    volumes:
      - ./api:/app
      - /app/node_modules
  mongo:
    image: mongo:latest
    container_name: dendriteai-mongo-c
    ports:
      - '27017:27017'
    volumes:
      - mongodata:/data/db
  client:
    build: ./client
    container_name: dendriteai-client-c
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true

volumes:
  mongodata:
